# Use a lighter base image
FROM golang:1.22.2-alpine AS builder

# Set necessary environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Create a directory for the app
WORKDIR /app

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the app
RUN go build -o climby .

# Use a minimal base image
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /app/climby .

# Expose the port
EXPOSE 3000

# Set default environment variables (can be overridden at runtime)
ARG PORT=3000
ARG DBPORT=5432
ARG HOST=192.168.122.159
ARG USERNAME=climby
ARG PASSWORD=123
ARG DB_URL="host=192.168.122.159 user=climby password=123 port=5432 sslmode=disable TimeZone=Europe/Madrid"

# Set runtime environment variables
ENV PORT=$PORT \
    DBPORT=$DBPORT \
    HOST=$HOST \
    USERNAME=$USERNAME \
    PASSWORD=$PASSWORD \
    DB_URL=$DB_URL

# Command to run the executable
CMD ["./climby"]