# Use a lighter base image
FROM golang:1.22.2-alpine AS builder

# Set necessary environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Create a directory for the app
WORKDIR /app

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the app
RUN go build -o climby .

# Use a minimal base image
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /app/climby .

# Copy the .env file
COPY .env .

# Expose the port
EXPOSE 3000

# Command to run the executable
ENTRYPOINT ["/app/entrypoint.sh"]